### ISSUE TITLE
An error message occurred while using Amar UI

### ISSUE THREAD

**Issue by andriannus** [tunaiku/amar-ui-web#16]
## Description
I use Amar UI on my Angular project. I have followed the quick start guide. But, when I use Amar UI on my SCSS file, I get several error messages like the picture below:
![Error Amar UI](https://user-images.githubusercontent.com/22554469/87177117-5108b780-c305-11ea-81fa-c79f725fc074.png)

## Minimal Reproduction
1. Install Amar UI with `npm`
2. Follow quick start guide to resolving `node_modules` path
3. Use Amar UI on my SCSS file with the following syntax:
`@import '@amar-ui-web/core/index.scss';`

**Comment by andriannus** [comment]
I have solved this error with install `node-sass` on my Angular project. Is this a good way?
If so, can you update the documentation?
Thank you

**Comment by dkk94** [comment]
> I have solved this error with install `node-sass` on my Angular project. Is this a good way?
> If so, can you update the documentation?
> Thank you

Happy that you solved the problem! Sure, let's put it in the documentation so the others know what to do if they face the same problem.
